server:
  port: 8081

  session:
    timeout: 86400
spring:
  #REDIS
  redis:
    database: 2
    host: localhost
    port: 6379
  freemarker:
    cache: true
    charset: "UTF-8"
    content-type: "text/html"
    enabled: true
    suffix: ".html"
    template-loader-path: "classpath:/templates/"
    request-context-attribute: "request"
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
api:
  gateway:
    url: "http://localhost:10000/api"
security:
  basic:
    enabled: false
  enabled: true
