
server:
  port: 8081

spring:
  #REDIS
  redis:
    database: 2
    host: localhost
    port: 6379
  activemq:
    in-memory: true
    pooled: false
    broker-url: "tcp://localhost:61616"
    user: "admin"
    password: "admin"
  freemarker:
    cache: true
    charset: "UTF-8"
    content-type: "text/html"
    enabled: true
    suffix: ".html"
    template-loader-path: "classpath:/templates/"
    request-context-attribute: "request"
jms:
    pub-sub-domain: true
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
framework:
  cache:
    expire: 86400
  mq:
    queues:
      - "common.queue"
      - "myqueue"
    topics:
      - "common.topic"
