
server:
  port: 8082

spring:
  #REDIS
  redis:
    database: 2
    host: 106.14.68.145
    port: 26379
  activemq:
    in-memory: true
    pooled: false
    broker-url: "tcp://localhost:61616"
    user: "admin"
    password: "admin"
  datasource:
    name: test
    url: jdbc:mysql://106.14.68.145:3306/ciip_usr?useSSL=false&characterEncoding=utf8
    username: root
    password: uf6btfvwnwx6b2wyivl1
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

jms:
    pub-sub-domain: true
mybatis:
  enabled: true
  typeAliasesPackage: "**.*.domain"
  mapperLocations: "classpath:/**/*/mappers/*.xml"
  enabledCache: true
  order: "BEFORE"
eureka:
  client:
    serviceUrl:
      defaultZone: "http://eureka-server:9002/eureka/"
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    preferIpAddress: true
    statusPageUrlPath: "/info"
    healthCheckUrlPath: "/health"
global:
  cache:
    expire: 86400
    database: 15
    host: 106.14.68.145
    port: 26379
    maxActive: 300
    maxIdle: 100
    maxWait: 1000
  mq:
    enabled: true
    queues:
      - "common.queue"
      - "myqueue"
    topics:
      - "common.topic"

swagger:
  basePackage: "com.esudian.usr"
  enabled: true
  title: "用户管理"
  description: "用户管理服务"
  version: "v1"
  contactName: "admin"
  contactUrl: "http://localhost:8082"
  contactEmail: "316311403@qq.com"
security:
  basic:
    enabled: false
flyway:
  enabled: true
  sql-migration-separator: "@"