
server:
  port: 8081

spring:
  #REDIS
  redis:
    database: 2
    host: localhost
    port: 6379
  activemq:
    in-memory: true
    pooled: false
    broker-url: "tcp://localhost:61616"
    user: "admin"
    password: "admin"
  datasource:
    name: test
    url: jdbc:mysql://localhost:49153/test?useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

jms:
    pub-sub-domain: true
mybatis:
  typeAliasesPackage: "**.*.domain"
  mapperLocations: "classpath:/**/*/mapper/*.xml"
  basePackage: "com.pudding.mappers"
  enabledCache: true
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
    healthcheck:
      enabled: true  
  instance:
    preferIpAddress: true
framework:
  cache:
    expire: 86400
  mq:
    queues:
      - "common.queue"
      - "myqueue"
    topics:
      - "common.topic"
