server:
  port: 8083

spring:
  #REDIS
  redis:
    database: 2
    host: 106.14.68.145
    port: 26379
  datasource:
    name: test
    url: jdbc:mysql://106.14.68.145:3306/ciip_mdm?useSSL=false&characterEncoding=utf8
    username: root
    password: uf6btfvwnwx6b2wyivl1
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  enabled: true
  typeAliasesPackage: "**.*.domain"
  mapperLocations: "classpath:/com/esudian/mdm/mappers/*.xml"
  enabledCache: true
  order: "BEFORE"
eureka:
  client:
    serviceUrl:
      defaultZone: "http://eureka-server:9002/eureka/"
    healthcheck:
      enabled: true
    lease:
      duration: 5
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    preferIpAddress: true
    statusPageUrlPath: "/info"
    healthCheckUrlPath: "/health"
global:
  cache:
    expire: 86400
    database: 15
    host: 106.14.68.145
    port: 26379
    maxActive: 300
    maxIdle: 100
    maxWait: 1000
swagger:
  basePackage: "com.esudian.mdm"
  enabled: true
  title: "主数据管理"
  description: "主数据管理服务"
  version: "v1"
  contactName: "admin"
  contactUrl: "http://localhost:8083"
  contactEmail: "316311403@qq.com"
flyway:
  enabled: true
  sql-migration-separator: "@"
security:
  basic:
    enabled: false

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
